name: Build and Release Android App (Internal Track)

on:
  workflow_dispatch: # Manual trigger

concurrency:
  group: google-play-deploy-skil
  cancel-in-progress: false

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.9"
          cache-disabled: true

      - name: Build Release App Bundle (.aab)
        working-directory: android
        run: |
          gradle :composeApp:bundleRelease --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: skil-lifestyle-release-aab
          path: android/composeApp/build/outputs/bundle/release/*.aab
